ServerName localhost

Listen 80

# Required Apache modules
LoadModule mpm_event_module modules/mod_mpm_event.so

LoadModule authz_core_module modules/mod_authz_core.so

LoadModule unixd_module modules/mod_unixd.so

LoadModule dir_module modules/mod_dir.so

LoadModule mime_module modules/mod_mime.so

LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

# Website
DocumentRoot "/usr/local/apache2/htdocs"

<Directory "/usr/local/apache2/htdocs">
    AllowOverride None
    Require all granted
</Directory>

# Serve index.html automatically
DirectoryIndex index.html

# Reverse proxy to Flask
ProxyPass        "/api/" "http://app:5000/api/"
ProxyPassReverse "/api/" "http://app:5000/api/"